---
name: e2e

'on':
  - push
  - pull_request

env:
  GOPROXY: https://proxy.golang.org
  GOPATH: ${{ github.workspace }}/go

permissions:
  contents: read

jobs:
  tests-e2e-scenarios-bare-metal:
    runs-on: ubuntu-24.04
    timeout-minutes: 70
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops
          fetch-depth: 3

      - name: Set up go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version-file: '${{ env.GOPATH }}/src/k8s.io/kops/go.mod'

      - name: dev/tasks/free-disk-space-on-github-actions-runner
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          dev/tasks/free-disk-space-on-github-actions-runner

      - name: tests/e2e/scenarios/bare-metal/run-test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          CHANGED_VERSION=$(git diff --name-only HEAD~2 | grep -E '^kops-version\.go$' || true)
          if [ -z "${CHANGED_VERSION}" ]
          then
            timeout 60m tests/e2e/scenarios/bare-metal/run-test
          else
            echo "kops-version.go has been modified, skipping test"
          fi
        env:
          ARTIFACTS: /tmp/artifacts

      - name: Archive production artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-e2e-scenarios-bare-metal
          path: /tmp/artifacts/

  tests-e2e-scenarios-bare-metal-ipv6:
    runs-on: ubuntu-24.04
    timeout-minutes: 70
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops
          fetch-depth: 3

      - name: Set up go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version-file: '${{ env.GOPATH }}/src/k8s.io/kops/go.mod'

      - name: dev/tasks/free-disk-space-on-github-actions-runner
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          dev/tasks/free-disk-space-on-github-actions-runner

      - name: tests/e2e/scenarios/bare-metal/run-test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          CHANGED_VERSION=$(git diff --name-only HEAD~2 | grep -E '^kops-version\.go$' || true)
          if [ -z "${CHANGED_VERSION}" ]
          then
            timeout 60m tests/e2e/scenarios/bare-metal/scenario-ipv6
          else
            echo "kops-version.go has been modified, skipping test"
          fi
        env:
          ARTIFACTS: /tmp/artifacts
      - name: Archive production artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-e2e-scenarios-bare-metal-ipv6
          path: /tmp/artifacts/
